import Head from 'next/head'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState, useEffect } from 'react'
const URL = 'https://momsbackend.herokuapp.com' 
const TWcound = 16
const startmoney = 100

export default function Home() {
  const [percentages, setPercentages] = useState(0)
  const [dates, setdates] = useState([])
  const [DisplayAddWeek, setDisplayAddWeek] = useState(false)



  useEffect(() => {
    
    axios({
      method: 'get',
      url: `${URL}/dates`
    }).then(response => {
      setPercentages(response.data.p)
      setdates(response.data.dates)
    })
  }, [])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <nav className={styles.nav}>
          <ul>
            <li>{"week's"}</li>
            <li>percentages</li>
            <li>expected p.</li>
            <li>e. m.</li>
            <li>r. m.</li>
          </ul>
        </nav>
        <div className={styles.section}>
          <ul>
            {console.log(dates)}
            {dates.map(date =>{
              const nova = dates.filter(sienna => sienna.week === date.week-1);
              console.log(nova);
              let zoe = 0
              if(nova.length > 0){
                zoe = (nova[0].money/100)*(100+date.expectedP)
                
                console.log('siennalois');
              } 
              else {
                zoe = startmoney
                console.log("nova");
              }
              console.log(Number(zoe));
              return (
                <li key={date.week}>
                  <div className={styles.sienna}>
                    <div>{date.week}</div>
                    <div>{date.percentage}%</div>
                    <div>{date.expectedP}%</div>
                    <div>{zoe}</div>
                    <div>{date.money}$</div>
                  </div>
                </li>
              )
            })}



          </ul>
        </div>
        <div onClick={()=>{setDisplayAddWeek(true)}} style={{color:'#6ca2ff', cursor: 'pointer', padding: '0 5px'}}>add week</div>

      {DisplayAddWeek?
        <AddWeek ld={dates[dates.length - 1]} p={percentages} />
      :null
      }
      </div>
    </div>
  )
}


const AddWeek = ({ld, p}) => {
  console.log(ld);
  const [weekI, setweekI] = useState("")
  const [percentage, setpercentage] = useState("")
  const [money, setmoney] = useState("")
  const [password, setpassword] = useState("")

  useEffect(() => {
    setweekI(ld.week+1)
  })

  const [SWW, setSWW] = useState(false)
  
  const submitAddWeek = (e) => {
    e.preventDefault();
    axios({
      method: 'post',
      url: `${URL}/date`,
      data: {
        password: password.toString(),
        data: {
            week: weekI,
            percentage: percentage,
            expectedP: p,
            money: money
        }
    }
    }).then(() =>{
      setSWW(false)
      setweekI(false)
      setpercentage(false)
      setmoney(false)
      setpassword(false)
    }).catch(err =>{
      setSWW(true);
    })
  }

  return (
    <div>
      <form style={{padding: '0 5px'}} onSubmit={submitAddWeek}>
        <div>
          <lable style={{display: "block", fontSize: "20px", paddingBottom: "4px"}}>week</lable>
          <input onChange={e=> setweekI(e.target.value)} value={weekI} style={{display: "block", width: "100%", fontSize: "25px"}} type="text" />
        </div>

        <div>
          <lable style={{display: "block", fontSize: "20px", paddingBottom: "4px"}}>percentage</lable>
          <input onChange={e=> {
            const v = e.target.value
            setpercentage(v)
            
            setmoney((ld.money/100)*(100+Number(v)))
          }} value={percentage} style={{display: "block", width: "100%", fontSize: "25px"}} type="text" />
        </div>

        <div>
          <lable style={{display: "block", fontSize: "20px", paddingBottom: "4px"}}>money</lable>
          <input onChange={e=> setmoney(e.target.value)} value={money} style={{display: "block", width: "100%", fontSize: "25px"}} type="text" />

        </div>
        
        <div>
          <lable style={{display: "block", fontSize: "20px", paddingBottom: "4px"}}>password</lable>
          <input onChange={e=> setpassword(e.target.value)} value={password} style={{display: "block", width: "100%", fontSize: "25px"}} type="password" />
        </div>
        <button style={{display: "block", width: "100%", fontSize: '30px', marginTop: "5px"}}type="submit"> 
          submit
        </button>

      </form>
      {SWW?
      "something went wrong":null}
    </div>
  )
}